#!/bin/bash
# table -h
# Creates a little bash table from piped

rminus(){
    printf "%$1s" | sed "s/ /$2/g"
}

opt_header=0

setzero(){
vertical="|"
corner[0]="+"
corner[1]="+"
corner[2]="+"
corner[3]="+"
torner[0]="+"
torner[1]="+"
torner[2]="+"
torner[3]="+"
cross="+"
horizontal="-"
}

setone(){
vertical="┃"
corner[0]="┏"
corner[1]="┓"
corner[2]="┗"
corner[3]="┛"
torner[0]="┳"
torner[1]="┻"
torner[2]="┫"
torner[3]="┣"
cross="╋"
horizontal="━"
}

settwo(){
vertical="│"
corner[0]="┌"
corner[1]="┐"
corner[2]="└"
corner[3]="┘"
torner[0]="┬"
torner[1]="┴"
torner[2]="┤"
torner[3]="├"
cross="┼"
horizontal="─"
}

setthree(){
vertical="│"
corner[0]="╭"
corner[1]="╮"
corner[2]="╰"
corner[3]="╯"
torner[0]="┬"
torner[1]="┴"
torner[2]="┤"
torner[3]="├"
cross="┼"
horizontal="─"
}

setfour(){
vertical="║"
corner[0]="╔"
corner[1]="╗"
corner[2]="╚"
corner[3]="╝"
torner[0]="╦"
torner[1]="╩"
torner[2]="╣"
torner[3]="╠"
cross="╬"
horizontal="═"
}



setzero

while getopts "hH:C:V:T:X:01234" a ; do
    case $a in
        "h")
            opt_header=1
            ;;
        "H")
            horizontal="$OPTARG"
            ;;
        "C")
            corner=(${OPTARG// / })
            
            if [ "${#corner[@]}" -lt 4 ] ; then
                corner[0]="$OPTARG"
                corner[1]="$OPTARG"
                corner[2]="$OPTARG"
                corner[3]="$OPTARG"
            fi
            ;;
        "V")
            vertical="$OPTARG"
            ;;

        "T")
            torner=(${OPTARG})

            if [ "${#torner[@]}" -lt 4 ] ; then
                torner[0]="$OPTARG"
                torner[1]="$OPTARG"
                torner[2]="$OPTARG"
                torner[3]="$OPTARG"
            fi
            ;;
        "X")
            cross="$OPTARG"
            ;;
        "1")
            setone
            ;;
        "0")
            setzero
            ;;
        "2")
            settwo
            ;;
        "3")
            setthree
            ;;
        "4")
            setfour
            ;;
    esac
done

fi=$(mktemp)
cols=$(tee $fi | awk '{for(i=1;i<=NF;i++)if(ar[i]<=length($i))ar[i]=length($i)}END{for(a in ar){ar[a]+=1;print ar[a]}}')

cols=(${cols})


rheader(){
printf "$1"
for i in "${!cols[@]}" ; do
    printf "$4"
    rminus "${cols[i]}" "$4"
    printf "$2"
done
printf "\b$3\n"
}

rheader "${corner[0]}" "${torner[0]}" "${corner[1]}" "$horizontal"

cat $fi | \
while read line ; do
    i=0
    printf "$vertical"
    for a in $line ; do
        printf " %-${cols[i]}s$vertical" $a
        let i="i+1"
    done
    printf "\n"

    if [ $opt_header -eq 1 ] ; then
        rheader "${torner[3]}" "${cross}" "${torner[2]}" "$horizontal"
        opt_header=0
    fi
done 
rheader "${corner[2]}" "${torner[1]}" "${corner[3]}" "$horizontal"
rm $fi


