#!/bin/bash
# table -h
# Creates a little bash table from piped

printhelp(){
echo """table:
    This programm will output a table fields are splitted by 
    spaces rows by newlines.

Usage:
    table [-STYLE] [-t] [-C CORNERS] [-T TJUNCS] [-H HORIZ] 
          [-V VERTIC] [-X CROSS] [-F FIELD]

Parameters:
    -STYLE      For style use 0,1,2,3,4
    -C CORNERS  Specify the four corners
    -T TJUNCS   The four T-Junctions
    -H HORIZ    Horizontal symbol
    -V VERTIC   Vertical symbol
    -X CROSS    The cross symbol
    -F FIELD    The field seperator for csv \";\"
Example:
    The following command:
        $ echo -e \"a a\\n b b\" | \\
        > table -t  -C \"A B C D\"  -X \"X\"  -T \"1 2 3 4\" \\
        > -H \"-\" -V \"|\"
    will yield:
        A---1---B
        | a | a |
        4---X---3
        | b | b |
        C---2---D
"""
}

rminus(){
    printf "%$1s" | sed "s/ /$2/g"
}

opt_header=0
fieldsep=" "

setzero(){
vertical="|"
corner[0]="+"
corner[1]="+"
corner[2]="+"
corner[3]="+"
torner[0]="+"
torner[1]="+"
torner[2]="+"
torner[3]="+"
cross="+"
horizontal="-"
}

setone(){
vertical="┃"
corner[0]="┏"
corner[1]="┓"
corner[2]="┗"
corner[3]="┛"
torner[0]="┳"
torner[1]="┻"
torner[2]="┫"
torner[3]="┣"
cross="╋"
horizontal="━"
}

settwo(){
vertical="│"
corner[0]="┌"
corner[1]="┐"
corner[2]="└"
corner[3]="┘"
torner[0]="┬"
torner[1]="┴"
torner[2]="┤"
torner[3]="├"
cross="┼"
horizontal="─"
}

setthree(){
vertical="│"
corner[0]="╭"
corner[1]="╮"
corner[2]="╰"
corner[3]="╯"
torner[0]="┬"
torner[1]="┴"
torner[2]="┤"
torner[3]="├"
cross="┼"
horizontal="─"
}

setfour(){
vertical="║"
corner[0]="╔"
corner[1]="╗"
corner[2]="╚"
corner[3]="╝"
torner[0]="╦"
torner[1]="╩"
torner[2]="╣"
torner[3]="╠"
cross="╬"
horizontal="═"
}



setzero

while getopts "htH:C:V:T:X:01234S:F:" a ; do
    case $a in
        "F")
            fieldsep="$OPTARG"
            ;;
        "S")
            rowsep="$OPTARG"
            ;;
        "t")
            opt_header=1
            ;;
        "H")
            horizontal="$OPTARG"
            ;;
        "C")
            corner=(${OPTARG// / })
            
            if [ "${#corner[@]}" -lt 4 ] ; then
                corner[0]="$OPTARG"
                corner[1]="$OPTARG"
                corner[2]="$OPTARG"
                corner[3]="$OPTARG"
            fi
            ;;
        "V")
            vertical="$OPTARG"
            ;;

        "T")
            torner=(${OPTARG})

            if [ "${#torner[@]}" -lt 4 ] ; then
                torner[0]="$OPTARG"
                torner[1]="$OPTARG"
                torner[2]="$OPTARG"
                torner[3]="$OPTARG"
            fi
            ;;
        "X")
            cross="$OPTARG"
            ;;
        "1")
            setone
            ;;
        "0")
            setzero
            ;;
        "2")
            settwo
            ;;
        "3")
            setthree
            ;;
        "4")
            setfour
            ;;
        "h" | *)
            printhelp
            exit
            ;;
    esac
done

fi=$(mktemp)
cols=$(tee $fi | sed 's/\x1B\[[^m]*m//g' | awk -F "$fieldsep" '{for(i=1;i<=NF;i++)if(ar[i]<=length($i))ar[i]=length($i)}END{for(a in ar){ar[a]+=1;print ar[a]}}')

cols=(${cols})


rheader(){
printf "$1"
for i in "${!cols[@]}" ; do
    printf "$4"
    rminus "${cols[i]}" "$4"
    printf "$2"
done
printf "\b$3\n"
}

rheader "${corner[0]}" "${torner[0]}" "${corner[1]}" "$horizontal"

cat $fi | \
while read line ; do
    i=0
    printf "$vertical"

    echo $line | sed -E "s/[$fieldsep]+/\n/g" | \
    while read a ; do
        printf " $a"
        let j=${cols[i]}-$(echo $a | sed 's/\x1B\[[^m]*m//g' | wc -c)
        rminus "$j" " "
        printf " $vertical"
        let i="i+1"
    done
    printf "\n"

    if [ $opt_header -eq 1 ] ; then
        rheader "${torner[3]}" "${cross}" "${torner[2]}" "$horizontal"
        opt_header=0
    fi
done 
rheader "${corner[2]}" "${torner[1]}" "${corner[3]}" "$horizontal"
rm $fi


